<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Promise对象</title>
	<script type="text/javascript"></script>
</head>

<body>
</body>
<script>
	/*	1、Promise的含义
				Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6将其写进了语言标准，统一了用法，原生提供了Promise对象。

				所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。

				Promise对象有以下两个特点。

				（1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：Pending（进行中）、Resolved（已完成，又称 Fulfilled）和Rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。

				（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从Pending变为Resolved和从Pending变为Rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

				有了Promise对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，Promise对象提供统一的接口，使得控制异步操作更加容易。

				Promise也有一些缺点。首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于Pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

				如果某些事件不断地反复发生，一般来说，使用 stream 模式是比部署Promise更好的选择。
	*/

	//	2、基本用法：ES6规定，Promise对象是一个构造函数，用来生成Promise实例
	function timeout(ms) {
		return new Promise((resolve, reject) => {
			setTimeout(resolve, ms, 'done');
		})
	}

	timeout(1000).then((value) => {
		console.log(value);		//	将延迟1s后打印
	})

	let promise = new Promise((resolve, reject) => {
		console.log('Promise');
		resolve();
	})

	promise.then(() => {
		console.log('Resolved');
	})

	console.log('Hi!');
	//	Promise
	//	Hi!
	//	Resolved
	//	上面代码中，Promise新建后立即执行，所以首先输出的是"Promise"。然后，then方法指定的是回调函数，将在当前脚本所有同步任务执行完才会执行，所以"Resolved"最后输出。

	//	异步加载图片
	function loadImageAsync(url) {
		return new Promise(function(resolve, reject) {
			var image = new Image();
			
			image.onload = function() {
				resolve(image);
			};

			image.onerror = function() {
				reject(new Error('Could noe load image at ' + url));
			}

			image.src = url;
		});
	}
	//	上面代码中，使用Promise包装了一个图片加载的异步操作。如果加载成功，就调用resolve方法，否则就调用reject方法。

	var getJSON = function(url) {
	  var promise = new Promise(function(resolve, reject){
	    var client = new XMLHttpRequest();
	    client.open("GET", url);
	    client.onreadystatechange = handler;
	    client.responseType = "json";
	    client.setRequestHeader("Accept", "application/json");
	    client.send();

	    function handler() {
	      if (this.readyState !== 4) {
	        return;
	      }
	      if (this.status === 200) {
	        resolve(this.response);
	      } else {
	        reject(new Error(this.statusText));
	      }
	    };
	  });

	  return promise;
	};

	getJSON("/posts.json").then(function(json) {
	  console.log('Contents: ' + json);
	}, function(error) {
	  console.error('出错了', error);
	});

	//	上面代码中，getJSON是对XMLHttpRequest对象的封装，用于发出一个针对JSON数据的HTTP请求，并且返回一个Promise对象。需要注意的是，在getJSON内部，resolve函数和reject函数调用时，都带有参数。

	//	如果调用resolve函数和reject函数时带有参数，那么它们的参数会被传递给回调函数。reject函数的参数通常是Error对象的实例，表示抛出的错误；resolve函数的参数除了正常的值以外，还可能是另一个Promise实例，表示异步操作的结果有可能是一个值，也有可能是另一个异步操作。
	var p1 = new Promise((resolve, reject) => {
		setTimeout(() => reject(new Error('failError')), 3000)
	})

	var p2 = new Promise((resolve, reject) => {
		setTimeout(() => resolve(p1), 1000)
	})

	p2
		.then(result => console.log(result))
		.catch(error => console.log(error))
	//	Error: failError	是108行打印的

	//	上面代码中，p1是一个Promise，3秒之后变为rejected。p2的状态在1秒之后改变，resolve方法返回的是p1。由于p2返回的是一个Promise，导致p2自己的状态无效了，由p1的状态决定p2的状态。所以，后面的then语句都变成针对后者(p1)。又过了2秒，p1变为rejected，导致触发catch方法指定的回调函数。

	/*	3. Promise.prototype.then()
				Promise实例具有then方法，也就是说，then方法是定义在原型对象Promise.prototype上的。它的作用是为Promise实例添加状态改变时的回调函数。前面说过，then方法的第一个是Resolved状态的回调函数，第二个参数（可选）是Rejected状态的回调函数。

			then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面在调用另一个then方法。
	*/
	getJSON('/posts.json').then(function(json) {
		return json.post;
	}).then(function(post) {
		//	...
	})

	//	上面的代码使用then方法，依次指定了两个回调函数。第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数。

	//	采用链式的then，可以指定一组按照次序调用的回调函数。这时，前一个回调函数，有可能返回的还是一个Promise对象（即有异步操作），这时后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用。

	getJSON("/post/1.json").then(function(post) {
	  return getJSON(post.commentURL);
	}).then(function funcA(comments) {
	  console.log("Resolved: ", comments);
	}, function funcB(err){
	  console.log("Rejected: ", err);
	});

	//	上面代码中，第一个then方法指定的回调函数，返回的是另一个Promise对象。这时，第二个then方法指定的回调函数，就会等待这个行的Promise对象状态发生变化。如果变为Resolved，就调用funcA，如果状态为Rejected，就调用funcB。
	
	//	将上一段代码改成箭头函数
	get("/post/1.json").then((post) => getJSON(post.commentURL)).then(
		(comments) => console.log("Resolved: ", comments);
		(err) => console.log("Rejected: ", err);
	)

	//	4、Promise.prototype.catch() 方法是 .then(null, rejection)的别名,用于指定发生错误时的回调函数。
	getJSON('/posts.json').then(function(posts) {

	}).catch(function(error) {
		//	处理getJSON和前一个回调函数运行时发送的错误
		console.log('发生错误！', error);
	});
	
	//	上面代码中，getJSON方法返回一个 Promise 对象，如果该对象状态变为Resolved，则会调用then方法指定的回调函数；如果异步操作抛出错误，状态就会变为Rejected，就会调用catch方法指定的回调函数，处理这个错误。另外，then方法指定的回调函数，如果运行中抛出错误，也会被catch方法捕获。
	p.then((val) => console.log('fulfilled: ', val))
		.catch((err) => console.log('rejected', err));

	//	等同于
	p.then((val) => console.log('fulfilled:', val))
		.catch((err) => console.log('rejected', err));

	//	下面是一个例子
	var promise = new Promise((resolve, reject) => {
		throw new Error('test');
	});
	promise.catch(function(error) {
		console.log(error);
	});
	//	Error: test

	//	上面代码中，promise抛出一个错误，就被catch方法指定的回调函数捕获。注意，上面的写法与下面的两种写法是等价的。
	//	写法一：
	var promise = new Promise((resolve, reject) => {
		try {
			throw new Error('test');
		} catch(e) {
			reject(e);
		}
	});
	promise.catch((error) => {
		console.log(error);
	});

	//	写法二：
	var promise = new Promise((resolve, reject) => {
		reject(new Error('test'));
	});
	promise.catch((error) => {
		console.log(error);
	})

	//	如果Promise状态已经变成Resolved，再抛出错误时无效的
	var promise = new Promise(function(resolve, reject) {
		resolve('ok');
		throw new Error('test');
	});
	promise.then((value) => console.log(value) ).catch((error) => console.log(error));
	//	上面代码中，Promise在resolve语句后面，在抛出错误，不会被捕获，等于没有抛出。因为Promise的状态一旦改变，就永久保持改状态，不会再变了。

	//	Promise对象的错误具有“冒泡性质”，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获
	getJSON('/post/1.json').then(function(post) {
	  return getJSON(post.commentURL);
	}).then(function(comments) {
	  // some code
	}).catch(function(error) {
	  // 处理前面三个Promise产生的错误
	});
	//	上面代码中，一共有三个Promise对象：一个由getJSON产生，两个由then产生。它们之中任何一个抛出的错误，都会被最后一个catch捕获。

	//	一般来说，不要在then方法里面定义Reject状态的回调函数（即then的第二个参数），总是使用catch方法。
	// bad
	promise
	  .then(function(data) {
	    // success
	  }, function(err) {
	    // error
	  });

	// good
	promise
	  .then(function(data) { //cb
	    // success
	  })
	  .catch(function(err) {
	    // error
	  });
	//	上面代码中，第二种写法要好于第一种写法，理由是第二种写法可以捕获前面then方法执行中的错误，也更接近同步的写法（try/catch）。因此，建议总是使用catch方法，而不使用then方法的第二个参数。

	//	5、Promise.all()：Promise.all方法用于将多个Promise实例。包装成一个新的Promise实例。
	var p = Promise.all([p1, p2, p3]);
	//	上面代码中，Promise.all方法接受一个数组作为参数，p1、p2、p3都是Promise对象的实例，如果不是，就会先调用下面讲到的Promise.resolve方法，将参数转为Promise实例，再进一步处理。（Promise.all方法的参数可以不是数组，但必须具有Iterator接口，且返回的每个成员都是Promise实例。）
	/*	p的状态由p1、p2、p3决定，分成两种情况。
	（1）只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。
	（2）只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。*/

	var promises = [2, 3, 5, 7, 11, 13].map(function(id) {
		return getJSON(`/post/${id}.json`);
	});

	Promise.all(promise).then(function (posts) {
		//	...
	}).catch(function(reason) {
		//	...
	});
	//	上面代码中，promises是包含6个Promise实例的数组，只有这6个实例的状态都变成fulfilled，或者其中有一个变为rejected，才会调用Promise.all方法后面的回调函数。

	//	6、Promise.race()：Promise.race方法同样是将多个Promise实例，包装成一个新的Promise实例。
	var p = Promise.race([p1, p2, p3]);
	/*	上面代码中，只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。

	Promise.race方法的参数与Promise.all方法一样，如果不是 Promise 实例，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise 实例，再进一步处理。*/
	const p = Promise.race([
		fetch('/resource-that-may-take-a-while'),
		new Promise(function (resolve, reject) {
			setTimeout(() => reject(new Error('request timeout')), 5000)
		})
	]);
	p.then(response => console.log(response));
	p.catch(error => console.log(error));
	//	上面代码中，如果5秒之内fetch方法无法返回结果，变量p的状态就会变为rejected,从而触发catch方法指定的回调函数。
</script>

</html>